MIDI_CH            = 0
SAMPLING_RATE      = 15625
NOTE_NUMBER_MIN    = 24
NOTE_NUMBER_MAX    = 96
EG_UPDATE_INTERVAL = 25

SUB_OSC_LEAD = 0
SAW_LEAD     = 1
SQUERE_LEAD  = 2
SYNTH_PAD    = 3
SYNTH_BASS   = 4

NOTE_OFF              = 0x80
NOTE_ON               = 0x90
PROGRAM_CHANGE        = 0xC0
ACTIVE_SENSING        = 0xFE
