MIDI_CH = 0
SAMPLING_RATE = 15625
NOTE_NUMBER_MIN = 24
NOTE_NUMBER_MAX = 96

SUB_OSC_LEAD = 0
SAW_LEAD     = 1
SQUERE_LEAD  = 2
SYNTH_PAD    = 3
SYNTH_BASS   = 4

NOTE_ON               = (0x90 | MIDI_CH)
NOTE_OFF              = (0x80 | MIDI_CH)
PROGRAM_CHANGE        = (0xC0 | MIDI_CH)
ACTIVE_SENSING        = 0xFE
